### ISSUE TITLE
Preset dropdown list

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion-module-eventmaster#22]
1) '(' shows in preset dropdown list as '&#40;'

2) any chance of ordering list by preset number so it matches list in e2

**Comment by JeffreyDavidsz** [comment]
@DaveShep can you clarify the first?

**Comment by JeffreyDavidsz** [comment]
@DaveShep for the second one, It goes by id. That should be order of creation. There is a presetSno in the list that might be what you are looking for.

**Comment by DaveShep** [comment]
By creation is less useful. Typical usage is renumbering presets to fit a
group or sequence.

**Comment by DaveShep** [comment]
In the screenshot you can see the issue in the drop down list. the '(' character is shown as & # 40 ;

![Untitled](https://user-images.githubusercontent.com/8885671/56343685-571bf100-61b3-11e9-856d-6a19e70a8814.jpg)

**Comment by JeffreyDavidsz** [comment]
Seems that ) is being converted the right way but ( is not, it stay's:`$#40;`. 
I'm doing a `String.replace()` for now. I've also added a sort function on the preset list, it's sorted on the preset serial number now (no idea what it is though). As I don't have a live machine at this moment, could you check if this works for you? check build 933a18e

**Comment by DaveShep** [comment]
I have also found that the following characters are also not shown correctly (added spaces to prevent github translating):
< appears as 'l t ;'
> appears as '& g t ;'
& sometimes appears as 'a m p ;'

**Comment by DaveShep** [comment]
presetSno appears in the # column of Presets. Presets are always listed by increasing presetSno.

![2](https://user-images.githubusercontent.com/8885671/56360004-1506a580-61db-11e9-9374-63163bb833f0.jpg)

**Comment by JeffreyDavidsz** [comment]
This is what you want right?

**Comment by JeffreyDavidsz** [comment]
@DaveShep van you please test this? I would like to know if this solved the issue

**Comment by DaveShep** [comment]
With companion-1.3.0-856f227-1480-win64 I get this adding a Barco
Eventmaster instance

[image: em.jpg]

**Comment by JeffreyDavidsz** [comment]
Not getting your image...

**Comment by DaveShep** [comment]
https://drive.google.com/file/d/1EGxocd_dQY9g_vy1rVi_zYD1zolBUhRv/view?usp=drivesdk

**Comment by JeffreyDavidsz** [comment]
I've taken out a function but kept the sorting in. Can you test please?

**Comment by DaveShep** [comment]
Unable to test. In show now until end of day. I don't have another E2 job
for some time. Might need to recruit a tester or revert until you find one

**Comment by JeffreyDavidsz** [comment]
No problem

**Comment by JeffreyDavidsz** [comment]
Tested
