### ISSUE TITLE
typo in barco-eventmaster changeAuxContent

### ISSUE THREAD

**Issue by gerrylusk** [bitfocus/companion-module-eventmaster#5]
Mac v1.1.1 3048c43
built from github clone

While messing around with adding aux change buttons to Eventmaster, I've noticed that the code in barco-eventmaster/index.js in the changeAuxContent section uses auxDestIndex and id when they should be the same variable. Authors choice of which to use.

Also, I did get aux changing to work but I'm still learning Git, Node.js, and even js . Hopefully you'll be messing around in this file to add cues and can fix this as well. Thanks for the work that clearly went in to this and I'm happy to help test against real eventmaster hardware.

**Comment by JeffreyDavidsz** [comment]
Hi Gerry, I've updated the node-barco-eventmaster with Cue and 3d functions. As far as I can tell the complete API from the latest manual is in now. Everything else should be done by the xml module.
First bug was a typo, changed that. (by id). For your second stuff I've created a extra function when someone would like to use naming (I think because its in the API we should have a function for it). So standard is with just ID now. Pull request for @willosof is ready. Could you please test it? I have no live machine at the moment (Ascender day today ;-))

**Comment by gerrylusk** [comment]
I see the added cue stuff and will work on testing that. I’m pretty slow/new at some of this stuff but using it to learn and I’ll build something to test this.

I don’t see the fixed changeAuxContent but perhaps it isn’t committed yet or I don’t know what I’m doing. 

Thanks for the updates! I’ll keep you posted.

Gerry
glusk@mac.com <mailto:glusk@mac.com>

**Comment by willosof** [comment]
I'll go through the entire api one day soon to get in all recently added features. The update just did was just a merge of jeffreys pull request :)

**Comment by JeffreyDavidsz** [comment]
As far as I know, this is the latest version (downloaded the manual today because of release 6.2) only cues and 3d where missing

**Comment by JeffreyDavidsz** [comment]
@Gerry, the module needs to be updated at companion before you see the changes there, but you already could copy the index.js file over on your Dev machine.

**Comment by gerrylusk** [comment]
I don't see the bugfix in changeAuxContent but that's OK for now. 

I'm starting to test listCues. Turns out listCues does not need any params so I'm not sure what id-index of input config means in the Barco documentation. Maybe a typo? I'll ask them. params{} seems to work (without the inputCondigIndex stuff).

I'll test activateCue soon.

Thanks



curl -X POST -H "Content-Type: application/json" -d '{"params":{}, "method":"listCues", "id":"1234", "jsonrpc":"2.0"}' http://192.168.1.175:9999

{
    "id": "1234",
    "jsonrpc": "2.0",
    "result": {
        "response": [
            {
                "LockMode": 0,
                "Name": "Cue1.00",
                "cueSerialNo": 1,
                "id": 0
            },
            {
                "LockMode": 0,
                "Name": "Cue2.00",
                "cueSerialNo": 2,
                "id": 1
            }
        ],
        "success": 0
    }
}

**Comment by JeffreyDavidsz** [comment]
I see my latest commits are not in yet, will come

**Comment by gerrylusk** [comment]
listCues works after changing to params{}.
activateCue seems to work as expected.

**Comment by willosof** [comment]
Hmmmm, maybe I've overwritten your changes somehow, @JeffreyDavidsz ?? Anyways, i've pulled the barco-eventmaster change now, and upgraded it on npm and on in companion/eventmaster :)

**Comment by JeffreyDavidsz** [comment]
> I'm starting to test listCues. Turns out listCues does not need any params so I'm not sure what id-index of input config means in the Barco documentation. Maybe a typo? I'll ask them. params{} seems to work (without the inputCondigIndex stuff).

@gerrylusk let me know how they respond, tnx

**Comment by JeffreyDavidsz** [comment]
`eventmaster.prototype.changeAuxContent = function(id, pvwLastSrcIndex, pgmLastSrcIndex, cb) {
	var self = this;
	return self.query("changeAuxContent", { id: id, PvwLastSrcIndex: pvwLastSrcIndex, PgmLastSrcIndex: pgmLastSrcIndex }, cb);
}

eventmaster.prototype.changeAuxContentName = function(id, name, pvwLastSrcIndex, pgmLastSrcIndex, cb) {
	var self = this;
	return self.query("changeAuxContent", { id: id, name: name, PvwLastSrcIndex: pvwLastSrcIndex, PgmLastSrcIndex: pgmLastSrcIndex }, cb);
}`
these are the functions changed, @willosof updated it in companion, so after you run update.sh you should be able to use it.

**Comment by JeffreyDavidsz** [comment]
When I have the time lateron I'll write it in the module aswell for other users

**Comment by JeffreyDavidsz** [comment]
@gerrylusk did you test listCues() with parameter 0? Wondering if it returns undefined. Standard in de module is 0 at the moment.

**Comment by gerrylusk** [comment]
The only way I could get listCues to work was if I took out the variable altogether so that what got sent to the frame was {}.

**Comment by JeffreyDavidsz** [comment]
@gerrylusk I've added some stuff, you could refork and test it if you like. Only thing is that listCues will create an error while the node-barco-eventmaster isnt't updated yet. You could hack the parameter out ;-)

**Comment by gerrylusk** [comment]
LISTING CUES:

Changed the listCues in node-barco-eventmaster to remove the inputCondigIndex and leave only {} as the params.

Found a typo in eventmaster.js self.CHOICES_CUES.push had label: cue.cueName and should be cue.Name. With these two fixes, the cues show up in the button dropdown for Play Cue.

PLAYING / STOPING CUES:

You call ActivateCue when the function in node-barco-eventmaster is called ActivateCueById.

In function(System) you set the cue id to cueNumber but in the function(action) you refer to play_cue.


SEVERAL NOTES:

Often, a 0 ends up as NULL when sent to eventmaster. I’m not sure why. Also, it doesn’t always happen and I’m not sure why. This makes things like preset 1 or cue 1 (which have ids of 0) not work properly sometimes.

In eventmaster.js, the button actions log the id instead of the opt which is very unhelpful. (The id is literally “preset_in_pgm” where opt.preset_in_pgm should be logged.)

Would you add changing auxes to eventmaster.js? This needs a dropdown for Aux Destinations which needs an extra step to parse. I’ve added this to my fork so you can use whatever parts of that you want.

There’s something in the end that iterates over the presets and does something with a bank. It’s labeled function(updates). I have no idea what that part does but it’s marked as untested.

Thanks for all of the work on this!!

Gerry

**Comment by JeffreyDavidsz** [comment]
Hi @gerrylusk ,
Thanks! so for the first part it has been fixed already, it's in the node waiting to merge;

`eventmaster.prototype.listCues = function(cb) {
	var self = this;
	return self.query("listCues", {}, cb);
}`

- changed cueName to Name
- for the activateCueById, I'm not quite sure why you are still seeing the old function, in the module it's:

                case 'stop_cue':

			log('info','stop_cue:' + opt.stop_cue);

			if (self.eventmaster !== undefined) {
				self.eventmaster.activateCueById(parseInt(opt.stop_cue), 2, function(obj, res) {
					debug('activateCue response', res);
				}).on('error', function(err) {
					log('error','EventMaster Error: '+ err);
				});
			}
			break;
		case 'change_aux':
			log('info', 'change_aux, source: ${opt.source} destination ${opt.auxdestination}');

			if (self.eventmaster !== undefined) {
				self.eventmaster.changeAuxContent(parseInt(opt.source), -1, parseInt(opt.auxdestination), function(obj, res) {
					debug('changeAuxContent response', res);
				}).on('error', function(err) {
					log('error','EventMaster Error: '+ err);
				});
			}
			break;
`
As you see I added the aux also.

The last part is loading presets. You'll find them next to to log tab and it enables you to drag-drop the presets into companion button. It should load name and number. 

Thanks again @gerrylusk I'm working from the blind here without a machine, so you're a big help!

**Comment by gerrylusk** [comment]
OK, it's weird that I've deleted my entire companion directory and cloned again.
`git clone https://github.com/bitfocus/companion.git`
Then updated with:
`tools/update.sh`
After it all builds I've gotten an older version of eventmaster.js without the AUXDESTINATIONS.
But I copy/pasted the one I see in my web browser on github and I'm testing that (having also fixed the node-module for listCues).

First, I get an error that init.tcp() is not a function so I commented that out.
You mention that the right "Presets" pane is supposed to do something magic but for me it says "You have no instances that support presets at the moment."
Presets work fine. Cues work fine.
I see Aux dests added as a choice but destinations don't list. I suspect because the frame returns an array of two arrays, one for screens and one for auxes. If you look at my version you'll see that I had to deal with the nested array of destinations.

`{
    "id": "1234",
    "jsonrpc": "2.0",
    "result": {
        "response": {
            "AuxDestination": [
                {
                    "AuxStreamMode": 4,
                    "FrzMode": 0,
                    "Name": "AuxDest1",
                    "id": 0
                },
                {
                    "AuxStreamMode": 4,
                    "FrzMode": 0,
                    "Name": "AuxDest2",
                    "id": 1
                }
            ]
        },
        "success": 0
    }
}
`

**Comment by JeffreyDavidsz** [comment]
Ah I see, you are cloning companion where the updated module isn't included yet. You would need to clone or refork the companion-module-eventmaster :-) you could copy the cloned eventmaster.js into lib/module/eventmaster

**Comment by gerrylusk** [comment]
That’s me not really understanding github. Brute force works though. ;-)

**Comment by gerrylusk** [comment]
Any idea why 0 shows up as NULL and/or what to do about it? There seems to be something different about presets and cues and preset 0 seems to work but cue and source and auxdest 0 all show NULL and therefore don't work. Thoughts?


```
  lib/action found actions +0ms
ACTION RUN--------: { id: 'SJp0AmpfE',
  label: 'S1MR9eTfN:preset_in_pgm',
  instance: 'S1MR9eTfN',
  action: 'preset_in_pgm',
  options: { preset_in_pgm: '0' } }
  instance:eventmaster:S1MR9eTfN run action: preset_in_pgm +4s
  instance:eventmaster:S1MR9eTfN recall preset pgm response null +40ms
  lib/action trying to run bank 1 12 false +164ms
  lib/action trying to run bank 1 9 true +549ms
  lib/action found actions +0ms
ACTION RUN--------: { id: 'HymNoeaf4',
  label: 'S1MR9eTfN:play_cue',
  instance: 'S1MR9eTfN',
  action: 'play_cue',
  options: { cueNumber: null } }
  instance:eventmaster:S1MR9eTfN run action: play_cue +674ms
  instance:eventmaster:S1MR9eTfN activateCue response { jsonrpc: '2.0',
  result: { success: -1, response: null },
  id: '0' } +31ms
  lib/action trying to run bank 1 9 false +165ms

```

**Comment by JeffreyDavidsz** [comment]
Without actual data it is hard to say. You could check if the dropdown has its correct values (view pagesource). Is there a name and id? If so it's in the variable used by function(action). When there are all Name's and null's, the array is not filled correctly. Because we are working from different rest API's. Copy paste this as node-barco-eventmaster:
https://github.com/JeffreyDavidsz/node-barco-eventmaster/blob/master/index.js
You can paste this in lib/module/eventmaster/node_modules/barco-eventmaster/index.js
It might work as the functions are slightly different

**Comment by JeffreyDavidsz** [comment]
Allright @gerrylusk I've tested some stuff, CUES work and should be in the latest build. Also the predefined cues and presets with actual data/text is also working now, you can drag/drop on a button without retyping everytime. I removed the change Aux, because I need to check why the destination is not populating. As soon as I figured out whats happening I'll report back

**Comment by gerrylusk** [comment]
The destinations are an array of two arrays. 

result={AuxDestination{Name, id, etc}, ScreenDestination{Name, id, etc}}

So you'll see in my version of eventmaster.js that I couldn't use res the set of destinations, I had to set Auxes to res.AuxDestination and use Auxes as the set of destinations.

Hope this helps.

**Comment by JeffreyDavidsz** [comment]
@gerrylusk That was it! So that took me less time than I thought to figure out ;-)
It's finally in, very much thanks for your help!
There is one big plus, when using this, no destinations are selected, its a direct switch! So when somebody else needs to change an aux, give him a streamdeck and you're save behind the desk

**Comment by gerrylusk** [comment]
You’re welcome. I do the aux switch regularly with some custom software on a Pi and xkeys stick. Like a router panel for an aux out on my engineering monitor. Also good for the graphics op to see sources. 
Companion and Stream Deck will just make this easier and more versatile.
